FROM mcr.microsoft.com/mirror/docker/library/nginx:1.25

ARG VITE_BASE_PATH=/

COPY dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf.template
COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

ENV BASE_PATH=${VITE_BASE_PATH}

EXPOSE 80
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
