// <auto-generated />
using System;
using Domain.ValueObjects;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124115152_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.LocationUsers.LocationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_location_users");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_location_users_location_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_location_users_user_id");

                    b.ToTable("location_users", (string)null);
                });

            modelBuilder.Entity("Domain.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_locations_organisation_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Domain.OrganisationUsers.OrganisationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organisation_users");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_organisation_users_organisation_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organisation_users_user_id");

                    b.ToTable("organisation_users", (string)null);
                });

            modelBuilder.Entity("Domain.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Name>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.Property<Guid>("SubId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.LocationUsers.LocationUser", b =>
                {
                    b.HasOne("Domain.Locations.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_location_users_locations_location_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.LocationUsers.LocationUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_location_users_users_user_id");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Locations.Location", b =>
                {
                    b.HasOne("Domain.Organisations.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locations_organisations_organisation_id");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Domain.OrganisationUsers.OrganisationUser", b =>
                {
                    b.HasOne("Domain.Organisations.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_users_organisations_organisation_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.OrganisationUsers.OrganisationUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_users_users_user_id");

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
