// <auto-generated />
using System;
using Domain.ValueObjects;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109055934_Location_Types")]
    partial class Location_Types
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Forms.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHierarchical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hierarchical");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_data_sources_code");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_data_sources_created_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_data_sources_last_modified_by_id");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.DataSourceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("label");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("ParentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_item_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_data_source_items");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_data_source_items_created_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_data_source_items_last_modified_by_id");

                    b.HasIndex("ParentItemId")
                        .HasDatabaseName("ix_data_source_items_parent_item_id");

                    b.HasIndex("DataSourceId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_data_source_items_data_source_id_value");

                    b.HasIndex("DataSourceId", "ParentItemId", "DisplayOrder")
                        .HasDatabaseName("ix_data_source_items_data_source_id_parent_item_id_display_ord");

                    b.ToTable("data_source_items", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_form_definitions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_form_definitions_code");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_form_definitions_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_form_definitions_deleted_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_form_definitions_last_modified_by_id");

                    b.ToTable("form_definitions", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.FormField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionalRules")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditional_rules");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<Guid?>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("DataSourceParentValue")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("data_source_parent_value");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("field_key");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("field_type");

                    b.Property<Guid?>("FormSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_section_id");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_version_id");

                    b.Property<string>("HelpText")
                        .HasColumnType("text")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("label");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<Guid?>("ParentFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_field_id");

                    b.Property<string>("Placeholder")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("placeholder");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rules");

                    b.HasKey("Id")
                        .HasName("pk_form_fields");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_form_fields_created_by_id");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_form_fields_data_source_id");

                    b.HasIndex("FormSectionId")
                        .HasDatabaseName("ix_form_fields_form_section_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_form_fields_last_modified_by_id");

                    b.HasIndex("ParentFieldId")
                        .HasDatabaseName("ix_form_fields_parent_field_id");

                    b.HasIndex("FormVersionId", "FieldKey")
                        .IsUnique()
                        .HasDatabaseName("ix_form_fields_form_version_id_field_key");

                    b.ToTable("form_fields", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.FormFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("FormFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_field_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("label");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<Guid?>("TriggeredFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_field_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_form_field_options");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_form_field_options_created_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_form_field_options_last_modified_by_id");

                    b.HasIndex("TriggeredFieldId")
                        .HasDatabaseName("ix_form_field_options_triggered_field_id");

                    b.HasIndex("FormFieldId", "DisplayOrder")
                        .HasDatabaseName("ix_form_field_options_form_field_id_display_order");

                    b.ToTable("form_field_options", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.FormFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("text")
                        .HasColumnName("display_value");

                    b.Property<string>("FileMimeType")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_mime_type");

                    b.Property<string>("FileName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileReference")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("file_reference");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("FormFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_field_id");

                    b.Property<Guid>("FormSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_submission_id");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_form_field_values");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_form_field_values_created_by_id");

                    b.HasIndex("FormFieldId")
                        .HasDatabaseName("ix_form_field_values_form_field_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_form_field_values_last_modified_by_id");

                    b.HasIndex("FormSubmissionId", "FormFieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_form_field_values_form_submission_id_form_field_id");

                    b.ToTable("form_field_values", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.FormSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_version_id");

                    b.Property<string>("HelpText")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("help_text");

                    b.Property<string>("HelpUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("help_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("section_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_form_sections");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_form_sections_created_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_form_sections_last_modified_by_id");

                    b.HasIndex("FormVersionId", "SectionNumber")
                        .HasDatabaseName("ix_form_sections_form_version_id_section_number");

                    b.ToTable("form_sections", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTime?>("DraftSavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("draft_saved_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_version_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text")
                        .HasColumnName("review_notes");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_id");

                    b.Property<string>("SubmitterIpAddress")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("submitter_ip_address");

                    b.Property<string>("SubmitterUserAgent")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("submitter_user_agent");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_form_submissions");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_form_submissions_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_form_submissions_deleted_by_id");

                    b.HasIndex("FormVersionId")
                        .HasDatabaseName("ix_form_submissions_form_version_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_form_submissions_last_modified_by_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_form_submissions_reviewed_by_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_form_submissions_status");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_form_submissions_submitted_at");

                    b.HasIndex("SubmittedById")
                        .HasDatabaseName("ix_form_submissions_submitted_by_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_form_submissions_entity_type_entity_id");

                    b.ToTable("form_submissions", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.FormSubmissionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("FormSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_submission_id");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("new_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("previous_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_form_submission_histories");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_form_submission_histories_created_by_id");

                    b.HasIndex("FormSubmissionId")
                        .HasDatabaseName("ix_form_submission_histories_form_submission_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_form_submission_histories_last_modified_by_id");

                    b.ToTable("form_submission_histories", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.FormVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeNotes")
                        .HasColumnType("text")
                        .HasColumnName("change_notes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deprecated_at");

                    b.Property<Guid>("FormDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_definition_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedById")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_schema");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_form_versions");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_form_versions_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_form_versions_deleted_by_id");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_form_versions_last_modified_by_id");

                    b.HasIndex("PublishedById")
                        .HasDatabaseName("ix_form_versions_published_by_id");

                    b.HasIndex("FormDefinitionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_form_versions_form_definition_id_version_number");

                    b.ToTable("form_versions", (string)null);
                });

            modelBuilder.Entity("Domain.LocationUsers.LocationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_location_users");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_location_users_location_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_location_users_user_id");

                    b.ToTable("location_users", (string)null);
                });

            modelBuilder.Entity("Domain.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BSFHBranding")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bsfh_branding");

                    b.Property<string>("ClarificationComments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clarification_comments");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_opened");

                    b.Property<string>("DeliverySiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_site_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("location_types");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool>("NameChange")
                        .HasColumnType("boolean")
                        .HasColumnName("name_change");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_code");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_number");

                    b.Property<string>("StatusOfSite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_of_site");

                    b.Property<string>("TypeOfSite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_of_site");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_locations_organisation_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Domain.OrganisationUsers.OrganisationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organisation_users");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_organisation_users_organisation_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organisation_users_user_id");

                    b.ToTable("organisation_users", (string)null);
                });

            modelBuilder.Entity("Domain.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Name>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.Property<Guid>("SubId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Forms.DataSource", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_data_sources_users_created_by_id");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_data_sources_users_last_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Domain.Forms.DataSourceItem", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_data_source_items_users_created_by_id");

                    b.HasOne("Domain.Forms.DataSource", "DataSource")
                        .WithMany("Items")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_source_items_data_sources_data_source_temp_id");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_data_source_items_users_last_modified_by_id");

                    b.HasOne("Domain.Forms.DataSourceItem", "ParentItem")
                        .WithMany()
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_data_source_items_data_source_items_parent_item_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DataSource");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Domain.Forms.FormDefinition", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_definitions_users_created_by_id");

                    b.HasOne("Domain.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_definitions_users_deleted_by_id");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_definitions_users_last_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Domain.Forms.FormField", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_fields_users_created_by_id");

                    b.HasOne("Domain.Forms.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_form_fields_data_sources_data_source_id");

                    b.HasOne("Domain.Forms.FormSection", "FormSection")
                        .WithMany()
                        .HasForeignKey("FormSectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_form_fields_form_sections_form_section_id");

                    b.HasOne("Domain.Forms.FormVersion", "FormVersion")
                        .WithMany("Fields")
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_fields_form_versions_form_version_temp_id");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_fields_users_last_modified_by_id");

                    b.HasOne("Domain.Forms.FormField", "ParentField")
                        .WithMany()
                        .HasForeignKey("ParentFieldId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_form_fields_form_fields_parent_field_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DataSource");

                    b.Navigation("FormSection");

                    b.Navigation("FormVersion");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("ParentField");
                });

            modelBuilder.Entity("Domain.Forms.FormFieldOption", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_field_options_users_created_by_id");

                    b.HasOne("Domain.Forms.FormField", "FormField")
                        .WithMany("Options")
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_field_options_form_fields_form_field_id1");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_field_options_users_last_modified_by_id");

                    b.HasOne("Domain.Forms.FormField", "TriggeredField")
                        .WithMany()
                        .HasForeignKey("TriggeredFieldId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_form_field_options_form_fields_triggered_field_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("FormField");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("TriggeredField");
                });

            modelBuilder.Entity("Domain.Forms.FormFieldValue", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_field_values_users_created_by_id");

                    b.HasOne("Domain.Forms.FormField", "FormField")
                        .WithMany()
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_form_field_values_form_fields_form_field_id");

                    b.HasOne("Domain.Forms.FormSubmission", "FormSubmission")
                        .WithMany("FieldValues")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_field_values_form_submissions_form_submission_temp_id");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_field_values_users_last_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("FormField");

                    b.Navigation("FormSubmission");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Domain.Forms.FormSection", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_sections_users_created_by_id");

                    b.HasOne("Domain.Forms.FormVersion", "FormVersion")
                        .WithMany("Sections")
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_sections_form_versions_form_version_temp_id1");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_sections_users_last_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("FormVersion");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Domain.Forms.FormSubmission", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_submissions_users_created_by_id");

                    b.HasOne("Domain.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_submissions_users_deleted_by_id");

                    b.HasOne("Domain.Forms.FormVersion", "FormVersion")
                        .WithMany()
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_form_submissions_form_versions_form_version_id");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_submissions_users_last_modified_by_id");

                    b.HasOne("Domain.Users.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_submissions_users_reviewed_by_id");

                    b.HasOne("Domain.Users.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_submissions_users_submitted_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("FormVersion");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("ReviewedBy");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("Domain.Forms.FormSubmissionHistory", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_submission_histories_users_created_by_id");

                    b.HasOne("Domain.Forms.FormSubmission", "FormSubmission")
                        .WithMany("History")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_submission_histories_form_submissions_form_submission_");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_submission_histories_users_last_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("FormSubmission");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("Domain.Forms.FormVersion", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_versions_users_created_by_id");

                    b.HasOne("Domain.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_versions_users_deleted_by_id");

                    b.HasOne("Domain.Forms.FormDefinition", "FormDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("FormDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_versions_form_definitions_form_definition_temp_id");

                    b.HasOne("Domain.Users.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_versions_users_last_modified_by_id");

                    b.HasOne("Domain.Users.User", "PublishedBy")
                        .WithMany()
                        .HasForeignKey("PublishedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_form_versions_users_published_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("FormDefinition");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("PublishedBy");
                });

            modelBuilder.Entity("Domain.LocationUsers.LocationUser", b =>
                {
                    b.HasOne("Domain.Locations.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_location_users_locations_location_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.LocationUsers.LocationUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_location_users_users_user_id");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Locations.Location", b =>
                {
                    b.HasOne("Domain.Organisations.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locations_organisations_organisation_id");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Domain.OrganisationUsers.OrganisationUser", b =>
                {
                    b.HasOne("Domain.Organisations.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_users_organisations_organisation_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.OrganisationUsers.OrganisationUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_users_users_user_id");

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Forms.DataSource", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Forms.FormDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Domain.Forms.FormField", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Domain.Forms.FormSubmission", b =>
                {
                    b.Navigation("FieldValues");

                    b.Navigation("History");
                });

            modelBuilder.Entity("Domain.Forms.FormVersion", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
